// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudLocation
import GoogleCloudWKT
import GoogleLongRunning
import GoogleRpc
import GoogleCloudGax

/// Service describing handlers for resources
///
/// @Snippet(path: "AuditQuickstart")
public final class AuditClient: Clients.AuditProtocol, Sendable {
  let inner: any Clients.AuditStub
  let pollingErrorPolicy: GoogleCloudGax.PollingErrorPolicy
  let pollingBackoffPolicy: GoogleCloudGax.BackoffPolicy

  /// Creates a new `AuditClient` instance.
  public init(_ options: GoogleCloudGax.ClientOptions = .init()) throws {
    var inner: any Clients.AuditStub = try Clients.AuditTransport(options)
    inner = Clients.AuditRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.AuditLogging(inner, logger: logger)
    }
    self.inner = inner
    self.pollingErrorPolicy = options.pollingErrorPolicy
    self.pollingBackoffPolicy = options.pollingBackoffPolicy
  }

  /// Generates an audit scope report for a framework.
  ///
  /// @Snippet(path: "Audit_GenerateFrameworkAuditScopeReport")
  public func generateFrameworkAuditScopeReport(
    request: GenerateFrameworkAuditScopeReportRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudSecurityComplianceV1.GenerateFrameworkAuditScopeReportResponse {
    try await self.inner.generateFrameworkAuditScopeReport(request: request, options: options)
  }

  /// Creates an audit scope report for a framework.
  ///
  /// @Snippet(path: "Audit_CreateFrameworkAudit")
  public func createFrameworkAudit(
    request: CreateFrameworkAuditRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.createFrameworkAudit(request: request, options: options)
  }

  /// Creates an audit scope report for a framework.
  ///
  /// @Snippet(path: "Audit_CreateFrameworkAudit")
  public func createFrameworkAudit(
    withPolling: CreateFrameworkAuditRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<FrameworkAudit> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<FrameworkAudit>.State in
      return try op._extractStatus(FrameworkAudit.self)
    }
    let rawOp = try await self.createFrameworkAudit(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<FrameworkAudit>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Lists the framework audits for a given organization, folder, or project.
  ///
  /// @Snippet(path: "Audit_ListFrameworkAudits")
  public func listFrameworkAudits(
    request: ListFrameworkAuditsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudSecurityComplianceV1.ListFrameworkAuditsResponse {
    try await self.inner.listFrameworkAudits(request: request, options: options)
  }

  /// Lists the framework audits for a given organization, folder, or project.
  ///
  /// @Snippet(path: "Audit_ListFrameworkAudits")
  public func listFrameworkAudits(
    byItem: ListFrameworkAuditsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<FrameworkAudit, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws
        -> GoogleCloudSecurityComplianceV1.ListFrameworkAuditsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listFrameworkAudits(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Gets the details for a framework audit.
  ///
  /// @Snippet(path: "Audit_GetFrameworkAudit")
  public func getFrameworkAudit(
    request: GetFrameworkAuditRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudSecurityComplianceV1.FrameworkAudit {
    try await self.inner.getFrameworkAudit(request: request, options: options)
  }

  /// Lists information about the supported locations for this service.
  ///
  /// This method lists locations based on the resource scope provided in
  /// the [ListLocationsRequest.name][google.cloud.location.ListLocationsRequest.name] field: *
  /// **Global locations**: If `name` is empty, the method lists the
  /// public locations available to all projects. * **Project-specific
  /// locations**: If `name` follows the format
  /// `projects/{project}`, the method lists locations visible to that
  /// specific project. This includes public, private, or other
  /// project-specific locations enabled for the project.
  ///
  /// For gRPC and client library implementations, the resource name is
  /// passed as the `name` field. For direct service calls, the resource
  /// name is
  /// incorporated into the request path based on the specific service
  /// implementation and version.
  ///
  /// [google.cloud.location.ListLocationsRequest.name]: https://www.google.com/search?q=Swift+google.cloud.location+GoogleCloudLocation.ListLocationsRequest/name
  ///
  /// @Snippet(path: "Audit_ListLocations")
  public func listLocations(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLocation.ListLocationsResponse {
    try await self.inner.listLocations(request: request, options: options)
  }

  /// Lists information about the supported locations for this service.
  ///
  /// This method lists locations based on the resource scope provided in
  /// the [ListLocationsRequest.name][google.cloud.location.ListLocationsRequest.name] field: *
  /// **Global locations**: If `name` is empty, the method lists the
  /// public locations available to all projects. * **Project-specific
  /// locations**: If `name` follows the format
  /// `projects/{project}`, the method lists locations visible to that
  /// specific project. This includes public, private, or other
  /// project-specific locations enabled for the project.
  ///
  /// For gRPC and client library implementations, the resource name is
  /// passed as the `name` field. For direct service calls, the resource
  /// name is
  /// incorporated into the request path based on the specific service
  /// implementation and version.
  ///
  /// [google.cloud.location.ListLocationsRequest.name]: https://www.google.com/search?q=Swift+google.cloud.location+GoogleCloudLocation.ListLocationsRequest/name
  ///
  /// @Snippet(path: "Audit_ListLocations")
  public func listLocations(
    byItem: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudLocation.ListLocationsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listLocations(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Gets information about a location.
  ///
  /// @Snippet(path: "Audit_GetLocation")
  public func getLocation(
    request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLocation.Location {
    try await self.inner.getLocation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "Audit_ListOperations")
  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    try await self.inner.listOperations(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "Audit_ListOperations")
  public func listOperations(
    byItem: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleLongRunning.ListOperationsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listOperations(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "Audit_GetOperation")
  func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.getOperation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "Audit_DeleteOperation")
  public func deleteOperation(
    request: GoogleLongRunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    try await self.inner.deleteOperation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "Audit_CancelOperation")
  public func cancelOperation(
    request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    try await self.inner.cancelOperation(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `AuditClient`.
  ///
  /// To mock `AuditClient` change your functions to receive
  /// `some AuditProtocol` or `any AuditProtocol`
  /// and pass a mock implementation in your tests.
  public protocol AuditProtocol {
    /// See `AuditClient.generateFrameworkAuditScopeReport`.
    func generateFrameworkAuditScopeReport(request: GenerateFrameworkAuditScopeReportRequest)
      async throws -> GoogleCloudSecurityComplianceV1.GenerateFrameworkAuditScopeReportResponse

    /// See `AuditClient.generateFrameworkAuditScopeReport`.
    func generateFrameworkAuditScopeReport(
      scope: Swift.String,
      reportFormat: GenerateFrameworkAuditScopeReportRequest.Format,
      complianceFramework: Swift.String,
    ) async throws -> GoogleCloudSecurityComplianceV1.GenerateFrameworkAuditScopeReportResponse

    /// See `AuditClient.createFrameworkAudit`.
    func createFrameworkAudit(request: CreateFrameworkAuditRequest) async throws
      -> GoogleLongRunning.Operation

    /// See `AuditClient.createFrameworkAudit`.
    func createFrameworkAudit(withPolling: CreateFrameworkAuditRequest) async throws
      -> any GoogleCloudGax.PollableOperation<FrameworkAudit>

    /// See `AuditClient.createFrameworkAudit`.
    func createFrameworkAudit(
      parent: Swift.String,
      frameworkAudit: FrameworkAudit?,
      frameworkAuditId: Swift.String,
    ) async throws -> any GoogleCloudGax.PollableOperation<FrameworkAudit>

    /// See `AuditClient.listFrameworkAudits`.
    func listFrameworkAudits(request: ListFrameworkAuditsRequest) async throws
      -> GoogleCloudSecurityComplianceV1.ListFrameworkAuditsResponse

    /// See `AuditClient.listFrameworkAudits`.
    func listFrameworkAudits(
      byItem: ListFrameworkAuditsRequest
    ) throws -> any AsyncSequence<FrameworkAudit, Swift.Error>

    /// See `AuditClient.listFrameworkAudits`.
    func listFrameworkAudits(
      parent: Swift.String,
    ) throws -> any AsyncSequence<FrameworkAudit, Swift.Error>

    /// See `AuditClient.getFrameworkAudit`.
    func getFrameworkAudit(request: GetFrameworkAuditRequest) async throws
      -> GoogleCloudSecurityComplianceV1.FrameworkAudit

    /// See `AuditClient.getFrameworkAudit`.
    func getFrameworkAudit(
      name: Swift.String,
    ) async throws -> GoogleCloudSecurityComplianceV1.FrameworkAudit

    /// See `AuditClient.listLocations`.
    func listLocations(request: GoogleCloudLocation.ListLocationsRequest) async throws
      -> GoogleCloudLocation.ListLocationsResponse

    /// See `AuditClient.listLocations`.
    func listLocations(
      byItem: GoogleCloudLocation.ListLocationsRequest
    ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error>

    /// See `AuditClient.getLocation`.
    func getLocation(request: GoogleCloudLocation.GetLocationRequest) async throws
      -> GoogleCloudLocation.Location

    /// See `AuditClient.listOperations`.
    func listOperations(request: GoogleLongRunning.ListOperationsRequest) async throws
      -> GoogleLongRunning.ListOperationsResponse

    /// See `AuditClient.listOperations`.
    func listOperations(
      byItem: GoogleLongRunning.ListOperationsRequest
    ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error>

    /// See `AuditClient.listOperations`.
    func listOperations(
      name: Swift.String,
      filter: Swift.String,
    ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error>

    /// See `AuditClient.deleteOperation`.
    func deleteOperation(request: GoogleLongRunning.DeleteOperationRequest) async throws

    /// See `AuditClient.deleteOperation`.
    func deleteOperation(
      name: Swift.String,
    ) async throws

    /// See `AuditClient.cancelOperation`.
    func cancelOperation(request: GoogleLongRunning.CancelOperationRequest) async throws

    /// See `AuditClient.cancelOperation`.
    func cancelOperation(
      name: Swift.String,
    ) async throws

    /// See `AuditClient.generateFrameworkAuditScopeReport`.
    func generateFrameworkAuditScopeReport(
      request: GenerateFrameworkAuditScopeReportRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSecurityComplianceV1.GenerateFrameworkAuditScopeReportResponse

    /// See `AuditClient.createFrameworkAudit`.
    func createFrameworkAudit(
      request: CreateFrameworkAuditRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `AuditClient.createFrameworkAudit`.
    func createFrameworkAudit(
      withPolling: CreateFrameworkAuditRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<FrameworkAudit>

    /// See `AuditClient.listFrameworkAudits`.
    func listFrameworkAudits(
      request: ListFrameworkAuditsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSecurityComplianceV1.ListFrameworkAuditsResponse

    /// See `AuditClient.listFrameworkAudits`.
    func listFrameworkAudits(
      byItem: ListFrameworkAuditsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<FrameworkAudit, Swift.Error>

    /// See `AuditClient.getFrameworkAudit`.
    func getFrameworkAudit(
      request: GetFrameworkAuditRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSecurityComplianceV1.FrameworkAudit

    /// See `AuditClient.listLocations`.
    func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse

    /// See `AuditClient.listLocations`.
    func listLocations(
      byItem: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error>

    /// See `AuditClient.getLocation`.
    func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location

    /// See `AuditClient.listOperations`.
    func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse

    /// See `AuditClient.listOperations`.
    func listOperations(
      byItem: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error>

    /// See `AuditClient.deleteOperation`.
    func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    /// See `AuditClient.cancelOperation`.
    func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws
  }
}

// Default implementations
extension Clients.AuditProtocol {
  public func generateFrameworkAuditScopeReport(request: GenerateFrameworkAuditScopeReportRequest)
    async throws -> GoogleCloudSecurityComplianceV1.GenerateFrameworkAuditScopeReportResponse
  {
    try await self.generateFrameworkAuditScopeReport(request: request, options: .init())
  }

  public func generateFrameworkAuditScopeReport(
    request: GenerateFrameworkAuditScopeReportRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudSecurityComplianceV1.GenerateFrameworkAuditScopeReportResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func generateFrameworkAuditScopeReport(
    scope: Swift.String,
    reportFormat: GenerateFrameworkAuditScopeReportRequest.Format,
    complianceFramework: Swift.String,
  ) async throws -> GoogleCloudSecurityComplianceV1.GenerateFrameworkAuditScopeReportResponse {
    let request = GenerateFrameworkAuditScopeReportRequest().with {
      $0.scope = scope
      $0.reportFormat = reportFormat
      $0.complianceFramework = complianceFramework
    }
    return try await self.generateFrameworkAuditScopeReport(request: request)
  }

  public func createFrameworkAudit(request: CreateFrameworkAuditRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.createFrameworkAudit(request: request, options: .init())
  }

  public func createFrameworkAudit(
    request: CreateFrameworkAuditRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func createFrameworkAudit(withPolling: CreateFrameworkAuditRequest) async throws
    -> any GoogleCloudGax.PollableOperation<FrameworkAudit>
  {
    try await self.createFrameworkAudit(withPolling: withPolling, options: .init())
  }

  public func createFrameworkAudit(
    withPolling: CreateFrameworkAuditRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<FrameworkAudit> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<FrameworkAudit>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func createFrameworkAudit(
    parent: Swift.String,
    frameworkAudit: FrameworkAudit?,
    frameworkAuditId: Swift.String,
  ) async throws -> any GoogleCloudGax.PollableOperation<FrameworkAudit> {
    let request = CreateFrameworkAuditRequest().with {
      $0.parent = parent
      $0.frameworkAudit = frameworkAudit
      $0.frameworkAuditId = frameworkAuditId
    }
    return try await self.createFrameworkAudit(withPolling: request)
  }

  public func listFrameworkAudits(request: ListFrameworkAuditsRequest) async throws
    -> GoogleCloudSecurityComplianceV1.ListFrameworkAuditsResponse
  {
    try await self.listFrameworkAudits(request: request, options: .init())
  }

  public func listFrameworkAudits(
    request: ListFrameworkAuditsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudSecurityComplianceV1.ListFrameworkAuditsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listFrameworkAudits(
    byItem: ListFrameworkAuditsRequest
  ) throws -> any AsyncSequence<FrameworkAudit, Swift.Error> {
    try self.listFrameworkAudits(byItem: byItem, options: .init())
  }

  public func listFrameworkAudits(
    byItem: ListFrameworkAuditsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<FrameworkAudit, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws
        -> GoogleCloudSecurityComplianceV1.ListFrameworkAuditsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listFrameworkAudits(
    parent: Swift.String,
  ) throws -> any AsyncSequence<FrameworkAudit, Swift.Error> {
    let request = ListFrameworkAuditsRequest().with {
      $0.parent = parent
    }
    return try self.listFrameworkAudits(byItem: request)
  }

  public func getFrameworkAudit(request: GetFrameworkAuditRequest) async throws
    -> GoogleCloudSecurityComplianceV1.FrameworkAudit
  {
    try await self.getFrameworkAudit(request: request, options: .init())
  }

  public func getFrameworkAudit(
    request: GetFrameworkAuditRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudSecurityComplianceV1.FrameworkAudit {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getFrameworkAudit(
    name: Swift.String,
  ) async throws -> GoogleCloudSecurityComplianceV1.FrameworkAudit {
    let request = GetFrameworkAuditRequest().with {
      $0.name = name
    }
    return try await self.getFrameworkAudit(request: request)
  }

  public func listLocations(request: GoogleCloudLocation.ListLocationsRequest) async throws
    -> GoogleCloudLocation.ListLocationsResponse
  {
    try await self.listLocations(request: request, options: .init())
  }

  public func listLocations(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLocation.ListLocationsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listLocations(
    byItem: GoogleCloudLocation.ListLocationsRequest
  ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
    try self.listLocations(byItem: byItem, options: .init())
  }

  public func listLocations(
    byItem: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudLocation.ListLocationsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func getLocation(request: GoogleCloudLocation.GetLocationRequest) async throws
    -> GoogleCloudLocation.Location
  {
    try await self.getLocation(request: request, options: .init())
  }

  public func getLocation(
    request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLocation.Location {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listOperations(request: GoogleLongRunning.ListOperationsRequest) async throws
    -> GoogleLongRunning.ListOperationsResponse
  {
    try await self.listOperations(request: request, options: .init())
  }

  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listOperations(
    byItem: GoogleLongRunning.ListOperationsRequest
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    try self.listOperations(byItem: byItem, options: .init())
  }

  public func listOperations(
    byItem: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleLongRunning.ListOperationsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listOperations(
    name: Swift.String,
    filter: Swift.String,
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    let request = GoogleLongRunning.ListOperationsRequest().with {
      $0.name = name
      $0.filter = filter
    }
    return try self.listOperations(byItem: request)
  }

  public func getOperation(request: GoogleLongRunning.GetOperationRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.getOperation(request: request, options: .init())
  }

  public func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getOperation(
    name: Swift.String,
  ) async throws -> GoogleLongRunning.Operation {
    let request = GoogleLongRunning.GetOperationRequest().with {
      $0.name = name
    }
    return try await self.getOperation(request: request)
  }

  public func deleteOperation(request: GoogleLongRunning.DeleteOperationRequest) async throws {
    try await self.deleteOperation(request: request, options: .init())
  }

  public func deleteOperation(
    request: GoogleLongRunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func deleteOperation(
    name: Swift.String,
  ) async throws {
    let request = GoogleLongRunning.DeleteOperationRequest().with {
      $0.name = name
    }
    try await self.deleteOperation(request: request)
  }

  public func cancelOperation(request: GoogleLongRunning.CancelOperationRequest) async throws {
    try await self.cancelOperation(request: request, options: .init())
  }

  public func cancelOperation(
    request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func cancelOperation(
    name: Swift.String,
  ) async throws {
    let request = GoogleLongRunning.CancelOperationRequest().with {
      $0.name = name
    }
    try await self.cancelOperation(request: request)
  }
}
