// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// A Common Expression Language (CEL) expression that's used to create a rule.
public struct CELExpression: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The logical expression in CEL. The maximum length of the
  /// condition is 1000 characters. For more information, see [CEL
  /// expression](https://cloud.google.com/security-command-center/docs/compliance-manager-write-cel-expressions).
  public var expression: Swift.String = Swift.String()

  /// The criteria of the CEL expression.
  public var criteria: OneOf_Criteria? = nil

  /// Initialize a new instance of `CELExpression`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CELExpression().with { $0.resourceTypesValues = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case resourceTypesValues = "resourceTypesValues"
    case expression = "expression"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.expression = try container.decode(Swift.String.self, forKey: .expression)

    var criteria: OneOf_Criteria? = nil
    let criteriaCheckAndSet = {
      if criteria != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'criteria'"))
      }
      criteria = $0
    }
    if let resourceTypesValues = try container.decodeIfPresent(
      StringList?.self, forKey: .resourceTypesValues)
    {
      try criteriaCheckAndSet(.resourceTypesValues(resourceTypesValues))
    }
    self.criteria = criteria
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.expression, forKey: .expression)

    if let choice = self.criteria {
      switch choice {
      case .resourceTypesValues(let value):
        try container.encode(value, forKey: .resourceTypesValues)
      }
    }
  }

  /// The criteria of the CEL expression.
  public enum OneOf_Criteria: Codable, Equatable, Sendable {
    /// The resource instance types on which this expression is defined.
    /// The format is `<SERVICE_NAME>/<type>`.
    /// For example: `compute.googleapis.com/Instance`
    indirect case resourceTypesValues(StringList?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.cloudsecuritycompliance.v1.CELExpression"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
