// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// The details of a cloud control.
public struct CloudControlDetails: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The name of the cloud control, in one of the following formats:
  /// `organizations/{organization}/locations/{location}/cloudControls/{cloud_control}`
  /// or
  /// `projects/{project}/locations/{location}/cloudControls/{cloud_control}`.
  ///
  /// The only supported location is `global`.
  public var name: Swift.String = Swift.String()

  /// Required. The major version of the cloud control.
  public var majorRevisionId: Swift.Int64 = Swift.Int64()

  /// Optional. Parameters are key-value pairs that let you provide your custom
  /// location requirements, environment requirements, or other settings that are
  /// relevant to the cloud control. An example parameter is
  /// `{"name": "location","value": "us-west-1"}`.
  public var parameters: [Parameter] = []

  /// Initialize a new instance of `CloudControlDetails`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CloudControlDetails().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.cloudsecuritycompliance.v1.CloudControlDetails"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
