// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// The cloud control report.
public struct CloudControlReport: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The name of the cloud control.
  public var cloudControl: Swift.String = Swift.String()

  /// The display name of the cloud control.
  public var displayName: Swift.String = Swift.String()

  /// The description of the cloud control.
  public var description: Swift.String = Swift.String()

  /// The list of categories for the cloud control.
  public var categories: [Swift.String] = []

  /// The list of similar controls.
  public var similarControls: [SimilarControls] = []

  /// The type of the cloud control.
  public var cloudControlType: CloudControl.Type_ = CloudControl.Type_()

  /// The category of the finding.
  public var findingCategory: Swift.String = Swift.String()

  /// The list of rules that correspond to the cloud control.
  public var rules: [Rule] = []

  /// The severity of the finding.
  public var findingSeverity: Severity = Severity()

  /// The enforcement mode of the cloud control.
  public var enforcementMode: EnforcementMode = EnforcementMode()

  /// The name of the cloud control deployment.
  public var cloudControlDeployment: Swift.String = Swift.String()

  /// The major revision ID of the cloud control.
  public var majorRevisionId: Swift.Int64 = Swift.Int64()

  /// The minor revision ID of the cloud control.
  public var minorRevisionId: Swift.Int64 = Swift.Int64()

  /// The major revision IDs of the frameworks that the cloud control belongs to.
  public var frameworkMajorRevisionIds: [Swift.Int64] = []

  /// The assessment details of the cloud control.
  public var assessmentDetails: OneOf_AssessmentDetails? = nil

  /// Initialize a new instance of `CloudControlReport`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CloudControlReport().with { $0.manualCloudControlAssessmentDetails = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case manualCloudControlAssessmentDetails = "manualCloudControlAssessmentDetails"
    case cloudControlAssessmentDetails = "cloudControlAssessmentDetails"
    case cloudControl = "cloudControl"
    case displayName = "displayName"
    case description = "description"
    case categories = "categories"
    case similarControls = "similarControls"
    case cloudControlType = "cloudControlType"
    case findingCategory = "findingCategory"
    case rules = "rules"
    case findingSeverity = "findingSeverity"
    case enforcementMode = "enforcementMode"
    case cloudControlDeployment = "cloudControlDeployment"
    case majorRevisionId = "majorRevisionId"
    case minorRevisionId = "minorRevisionId"
    case frameworkMajorRevisionIds = "frameworkMajorRevisionIds"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.cloudControl = try container.decode(Swift.String.self, forKey: .cloudControl)
    self.displayName = try container.decode(Swift.String.self, forKey: .displayName)
    self.description = try container.decode(Swift.String.self, forKey: .description)
    self.categories = try container.decode([Swift.String].self, forKey: .categories)
    self.similarControls = try container.decode([SimilarControls].self, forKey: .similarControls)
    self.cloudControlType = try container.decode(CloudControl.Type_.self, forKey: .cloudControlType)
    self.findingCategory = try container.decode(Swift.String.self, forKey: .findingCategory)
    self.rules = try container.decode([Rule].self, forKey: .rules)
    self.findingSeverity = try container.decode(Severity.self, forKey: .findingSeverity)
    self.enforcementMode = try container.decode(EnforcementMode.self, forKey: .enforcementMode)
    self.cloudControlDeployment = try container.decode(
      Swift.String.self, forKey: .cloudControlDeployment)
    self.majorRevisionId = try container.decode(Swift.Int64.self, forKey: .majorRevisionId)
    self.minorRevisionId = try container.decode(Swift.Int64.self, forKey: .minorRevisionId)
    self.frameworkMajorRevisionIds = try container.decode(
      [Swift.Int64].self, forKey: .frameworkMajorRevisionIds)

    var assessmentDetails: OneOf_AssessmentDetails? = nil
    let assessmentDetailsCheckAndSet = {
      if assessmentDetails != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'assessmentDetails'"))
      }
      assessmentDetails = $0
    }
    if let manualCloudControlAssessmentDetails = try container.decodeIfPresent(
      ManualCloudControlAssessmentDetails?.self, forKey: .manualCloudControlAssessmentDetails)
    {
      try assessmentDetailsCheckAndSet(
        .manualCloudControlAssessmentDetails(manualCloudControlAssessmentDetails))
    }
    if let cloudControlAssessmentDetails = try container.decodeIfPresent(
      CloudControlAssessmentDetails?.self, forKey: .cloudControlAssessmentDetails)
    {
      try assessmentDetailsCheckAndSet(
        .cloudControlAssessmentDetails(cloudControlAssessmentDetails))
    }
    self.assessmentDetails = assessmentDetails
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.cloudControl, forKey: .cloudControl)
    try container.encode(self.displayName, forKey: .displayName)
    try container.encode(self.description, forKey: .description)
    try container.encode(self.categories, forKey: .categories)
    try container.encode(self.similarControls, forKey: .similarControls)
    try container.encode(self.cloudControlType, forKey: .cloudControlType)
    try container.encode(self.findingCategory, forKey: .findingCategory)
    try container.encode(self.rules, forKey: .rules)
    try container.encode(self.findingSeverity, forKey: .findingSeverity)
    try container.encode(self.enforcementMode, forKey: .enforcementMode)
    try container.encode(self.cloudControlDeployment, forKey: .cloudControlDeployment)
    try container.encode(self.majorRevisionId, forKey: .majorRevisionId)
    try container.encode(self.minorRevisionId, forKey: .minorRevisionId)
    try container.encode(self.frameworkMajorRevisionIds, forKey: .frameworkMajorRevisionIds)

    if let choice = self.assessmentDetails {
      switch choice {
      case .manualCloudControlAssessmentDetails(let value):
        try container.encode(value, forKey: .manualCloudControlAssessmentDetails)
      case .cloudControlAssessmentDetails(let value):
        try container.encode(value, forKey: .cloudControlAssessmentDetails)
      }
    }
  }

  /// The assessment details of the cloud control.
  public enum OneOf_AssessmentDetails: Codable, Equatable, Sendable {
    /// The details of a manual cloud control assessment.
    indirect case manualCloudControlAssessmentDetails(ManualCloudControlAssessmentDetails?)
    /// The details of a cloud control assessment.
    indirect case cloudControlAssessmentDetails(CloudControlAssessmentDetails?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.cloudsecuritycompliance.v1.CloudControlReport"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
