// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// A cloud control deployment represents the deployment of a particular cloud
/// control on a target resource. Supported target resources are
/// `organizations/{organizationID}`, `folders/{folderID}`, and
/// `projects/{projectID}`.
public struct CloudControlDeployment: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Identifier. The name for the cloud control deployment, in the format
  /// `organizations/{organization}/locations/{location}/cloudControlDeployments/{cloud_control_deployment}`
  /// or
  /// `projects/{project}/locations/{location}/cloudControlDeployments/{cloud_control_deployment}`.
  /// The only supported location is `global`.
  public var name: Swift.String = Swift.String()

  /// Required. The details of the target resource that the cloud control is
  /// deployed You can use an existing target resource or create a new target.
  public var targetResourceConfig: TargetResourceConfig? = nil

  /// Output only. The resource that the cloud control is deployed on, in one of
  /// the following formats:
  ///
  /// - `organizations/{organizationID}`
  /// - `folders/{folderID}`
  /// - `projects/{projectID}`
  public var targetResource: Swift.String = Swift.String()

  /// Required. The deployment mode and parameters for the cloud control.
  public var cloudControlMetadata: CloudControlMetadata? = nil

  /// Optional. A friendly description for the cloud control deployment.
  public var description: Swift.String = Swift.String()

  /// Output only. The state of the cloud control deployment.
  public var deploymentState: DeploymentState = DeploymentState()

  /// Output only. The time when the resource was created.
  public var createTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. The time when the resource was last updated.
  public var updateTime: GoogleCloudWkt.Timestamp? = nil

  /// Optional. To prevent concurrent updates from overwriting each other,
  /// provide the `etag` when you update a cloud control deployment. You can also
  /// provide the `etag` when you delete a cloud control deployment to help
  /// ensure that you're deleting the intended version of the
  /// deployment.
  public var etag: Swift.String = Swift.String()

  /// Output only. The cloud control after the given parameters are substituted.
  public var parameterSubstitutedCloudControl: CloudControl? = nil

  /// Output only. The references to the framework deployments that this cloud
  /// control deployment is part of. A cloud control deployment can be part of
  /// multiple framework deployments.
  public var frameworkDeploymentReferences: [FrameworkDeploymentReference] = []

  /// Output only. The display name of the target resource.
  public var targetResourceDisplayName: Swift.String = Swift.String()

  /// Initialize a new instance of `CloudControlDeployment`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CloudControlDeployment().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.cloudsecuritycompliance.v1.CloudControlDeployment"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
