// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// The details for a cloud control group.
public struct CloudControlGroupAuditDetails: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Output only. The ID of the cloud control group.
  public var cloudControlGroupId: Swift.String = Swift.String()

  /// Output only. The display name of the cloud control group.
  public var displayName: Swift.String = Swift.String()

  /// Output only. The description of the cloud control group.
  public var description: Swift.String = Swift.String()

  /// Output only. The responsibility type.
  public var responsibilityType: Swift.String = Swift.String()

  /// Output only. The description of Google's responsibility.
  public var googleResponsibilityDescription: Swift.String = Swift.String()

  /// Output only. The implementation of Google's responsibility.
  public var googleResponsibilityImplementation: Swift.String = Swift.String()

  /// Output only. The description of your responsibility.
  public var customerResponsibilityDescription: Swift.String = Swift.String()

  /// Output only. The implementation of your responsibility.
  public var customerResponsibilityImplementation: Swift.String = Swift.String()

  /// Output only. The compliance state of the control group.
  public var complianceState: ComplianceState = ComplianceState()

  /// Output only. The ID of the regulatory control.
  public var controlId: Swift.String = Swift.String()

  /// Output only. The control family.
  public var controlFamily: ControlFamily? = nil

  /// Output only. The details for the cloud controls within this group.
  public var cloudControlDetails: [CloudControlAuditDetails] = []

  /// Output only. The summary of the report.
  public var reportSummary: ReportSummary? = nil

  /// Initialize a new instance of `CloudControlGroupAuditDetails`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CloudControlGroupAuditDetails().with { $0.cloudControlGroupId = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return
      "type.googleapis.com/google.cloud.cloudsecuritycompliance.v1.CloudControlGroupAuditDetails"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
