// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudLocation
import GoogleCloudWKT
import GoogleLongRunning
import GoogleCloudGax

/// Config Service manages compliance frameworks, cloud controls, and their
/// configurations.
///
/// @Snippet(path: "ConfigQuickstart")
public final class ConfigClient: Clients.ConfigProtocol, Sendable {
  let inner: any Clients.ConfigStub

  /// Creates a new `ConfigClient` instance.
  public init(_ options: GoogleCloudGax.ClientOptions = .init()) throws {
    var inner: any Clients.ConfigStub = try Clients.ConfigTransport(options)
    inner = Clients.ConfigRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.ConfigLogging(inner, logger: logger)
    }
    self.inner = inner
  }

  /// Lists the frameworks (both built-in and custom) that are available within
  /// the parent resource. The latest major version of each framework is
  /// returned.
  /// This method supports pagination.
  ///
  /// @Snippet(path: "Config_ListFrameworks")
  public func listFrameworks(
    request: ListFrameworksRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudSecurityComplianceV1.ListFrameworksResponse {
    try await self.inner.listFrameworks(request: request, options: options)
  }

  /// Lists the frameworks (both built-in and custom) that are available within
  /// the parent resource. The latest major version of each framework is
  /// returned.
  /// This method supports pagination.
  ///
  /// @Snippet(path: "Config_ListFrameworks")
  public func listFrameworks(
    byItem: ListFrameworksRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Framework, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudSecurityComplianceV1.ListFrameworksResponse
      in
      var request = byItem
      request.pageToken = token
      return try await self.listFrameworks(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Gets details about a framework.
  /// This method retrieves the latest major version of the framework.
  ///
  /// To retrieve a specific major version, include `major_revision_id` in
  /// the request.
  ///
  /// @Snippet(path: "Config_GetFramework")
  public func getFramework(
    request: GetFrameworkRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudSecurityComplianceV1.Framework {
    try await self.inner.getFramework(request: request, options: options)
  }

  /// Creates a custom framework in a given parent resource.
  /// You can't create built-in frameworks because those are managed by
  /// Google.
  ///
  /// @Snippet(path: "Config_CreateFramework")
  public func createFramework(
    request: CreateFrameworkRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudSecurityComplianceV1.Framework {
    try await self.inner.createFramework(request: request, options: options)
  }

  /// Updates a custom framework.
  /// This method allows for partial updates of a framework. Use the
  /// `update_mask` to specify which fields to update. Consider the following:
  ///
  /// - If you provide an `update_mask`, only the fields that are specified
  /// in the mask are updated.
  /// - If you don't provide an `update_mask`, all the fields that are present
  /// in the request's `framework` body are used to overwrite the existing
  /// resource.
  ///
  /// You can only update frameworks with the `CUSTOM` type.
  /// A successful update creates a new version of the framework.
  ///
  /// @Snippet(path: "Config_UpdateFramework")
  public func updateFramework(
    request: UpdateFrameworkRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudSecurityComplianceV1.Framework {
    try await self.inner.updateFramework(request: request, options: options)
  }

  /// Deletes a custom framework, including all its major and
  /// minor revisions. Consider the following:
  ///
  /// - You can't delete built-in frameworks. You can only delete frameworks
  ///   with type `CUSTOM`.
  /// - You can't delete frameworks that are deployed to a resource.
  /// - You can't restore a deleted framework. This action is permanent.
  ///
  /// @Snippet(path: "Config_DeleteFramework")
  public func deleteFramework(
    request: DeleteFrameworkRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    try await self.inner.deleteFramework(request: request, options: options)
  }

  /// Lists the cloud controls (both built-in and custom) that are available
  /// in a given parent resource. The latest major version of each cloud control
  /// is returned.
  /// This method supports pagination.
  ///
  /// @Snippet(path: "Config_ListCloudControls")
  public func listCloudControls(
    request: ListCloudControlsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudSecurityComplianceV1.ListCloudControlsResponse {
    try await self.inner.listCloudControls(request: request, options: options)
  }

  /// Lists the cloud controls (both built-in and custom) that are available
  /// in a given parent resource. The latest major version of each cloud control
  /// is returned.
  /// This method supports pagination.
  ///
  /// @Snippet(path: "Config_ListCloudControls")
  public func listCloudControls(
    byItem: ListCloudControlsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<CloudControl, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws
        -> GoogleCloudSecurityComplianceV1.ListCloudControlsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listCloudControls(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Gets details about a cloud control.
  /// This method retrieves the latest major version of a cloud control that
  /// you identify by name.
  ///
  /// By default, the latest major version of the cloud control is returned.
  /// To retrieve a specific major version, include `major_revision_id` in
  /// the request.
  ///
  /// @Snippet(path: "Config_GetCloudControl")
  public func getCloudControl(
    request: GetCloudControlRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudSecurityComplianceV1.CloudControl {
    try await self.inner.getCloudControl(request: request, options: options)
  }

  /// Creates a custom cloud control in a given parent
  /// resource.
  /// You can't create built-in cloud controls because those are managed by
  /// Google.
  ///
  /// @Snippet(path: "Config_CreateCloudControl")
  public func createCloudControl(
    request: CreateCloudControlRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudSecurityComplianceV1.CloudControl {
    try await self.inner.createCloudControl(request: request, options: options)
  }

  /// Updates a custom cloud control.
  /// This method allows for partial updates of a cloud control. Use the
  /// `update_mask` to specify which fields to update. Consider the following:
  ///
  /// - If you provide an `update_mask`, only the fields that are specified
  /// in the mask are updated.
  /// - If you don't provide an `update_mask`, all the fields that are present
  /// in the request's `cloud_control` body are used to overwrite the existing
  /// resource.
  ///
  /// You can only update cloud controls with the `CUSTOM` type.
  /// A successful update creates a new version of the cloud control.
  ///
  /// @Snippet(path: "Config_UpdateCloudControl")
  public func updateCloudControl(
    request: UpdateCloudControlRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudSecurityComplianceV1.CloudControl {
    try await self.inner.updateCloudControl(request: request, options: options)
  }

  /// Deletes a custom cloud control, including all its
  /// major and minor revisions. Consider the following:
  ///
  /// - You can't delete built-in cloud controls. You can only delete cloud
  ///   controls with type `CUSTOM`.
  /// - You can't delete cloud controls if any of the versions are referenced
  ///   by a framework.
  /// - You can't restore a deleted cloud control. This action is permanent.
  ///
  /// @Snippet(path: "Config_DeleteCloudControl")
  public func deleteCloudControl(
    request: DeleteCloudControlRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    try await self.inner.deleteCloudControl(request: request, options: options)
  }

  /// Lists information about the supported locations for this service.
  ///
  /// This method lists locations based on the resource scope provided in
  /// the [ListLocationsRequest.name][google.cloud.location.ListLocationsRequest.name] field: *
  /// **Global locations**: If `name` is empty, the method lists the
  /// public locations available to all projects. * **Project-specific
  /// locations**: If `name` follows the format
  /// `projects/{project}`, the method lists locations visible to that
  /// specific project. This includes public, private, or other
  /// project-specific locations enabled for the project.
  ///
  /// For gRPC and client library implementations, the resource name is
  /// passed as the `name` field. For direct service calls, the resource
  /// name is
  /// incorporated into the request path based on the specific service
  /// implementation and version.
  ///
  /// [google.cloud.location.ListLocationsRequest.name]: https://www.google.com/search?q=Swift+google.cloud.location+GoogleCloudLocation.ListLocationsRequest/name
  ///
  /// @Snippet(path: "Config_ListLocations")
  public func listLocations(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLocation.ListLocationsResponse {
    try await self.inner.listLocations(request: request, options: options)
  }

  /// Lists information about the supported locations for this service.
  ///
  /// This method lists locations based on the resource scope provided in
  /// the [ListLocationsRequest.name][google.cloud.location.ListLocationsRequest.name] field: *
  /// **Global locations**: If `name` is empty, the method lists the
  /// public locations available to all projects. * **Project-specific
  /// locations**: If `name` follows the format
  /// `projects/{project}`, the method lists locations visible to that
  /// specific project. This includes public, private, or other
  /// project-specific locations enabled for the project.
  ///
  /// For gRPC and client library implementations, the resource name is
  /// passed as the `name` field. For direct service calls, the resource
  /// name is
  /// incorporated into the request path based on the specific service
  /// implementation and version.
  ///
  /// [google.cloud.location.ListLocationsRequest.name]: https://www.google.com/search?q=Swift+google.cloud.location+GoogleCloudLocation.ListLocationsRequest/name
  ///
  /// @Snippet(path: "Config_ListLocations")
  public func listLocations(
    byItem: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudLocation.ListLocationsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listLocations(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Gets information about a location.
  ///
  /// @Snippet(path: "Config_GetLocation")
  public func getLocation(
    request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLocation.Location {
    try await self.inner.getLocation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "Config_ListOperations")
  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    try await self.inner.listOperations(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "Config_ListOperations")
  public func listOperations(
    byItem: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleLongRunning.ListOperationsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listOperations(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "Config_GetOperation")
  func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.getOperation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "Config_DeleteOperation")
  public func deleteOperation(
    request: GoogleLongRunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    try await self.inner.deleteOperation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "Config_CancelOperation")
  public func cancelOperation(
    request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    try await self.inner.cancelOperation(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `ConfigClient`.
  ///
  /// To mock `ConfigClient` change your functions to receive
  /// `some ConfigProtocol` or `any ConfigProtocol`
  /// and pass a mock implementation in your tests.
  public protocol ConfigProtocol {
    /// See `ConfigClient.listFrameworks`.
    func listFrameworks(request: ListFrameworksRequest) async throws
      -> GoogleCloudSecurityComplianceV1.ListFrameworksResponse

    /// See `ConfigClient.listFrameworks`.
    func listFrameworks(
      byItem: ListFrameworksRequest
    ) throws -> any AsyncSequence<Framework, Swift.Error>

    /// See `ConfigClient.listFrameworks`.
    func listFrameworks(
      parent: Swift.String,
    ) throws -> any AsyncSequence<Framework, Swift.Error>

    /// See `ConfigClient.getFramework`.
    func getFramework(request: GetFrameworkRequest) async throws
      -> GoogleCloudSecurityComplianceV1.Framework

    /// See `ConfigClient.getFramework`.
    func getFramework(
      name: Swift.String,
    ) async throws -> GoogleCloudSecurityComplianceV1.Framework

    /// See `ConfigClient.createFramework`.
    func createFramework(request: CreateFrameworkRequest) async throws
      -> GoogleCloudSecurityComplianceV1.Framework

    /// See `ConfigClient.createFramework`.
    func createFramework(
      parent: Swift.String,
      framework: Framework?,
      frameworkId: Swift.String,
    ) async throws -> GoogleCloudSecurityComplianceV1.Framework

    /// See `ConfigClient.updateFramework`.
    func updateFramework(request: UpdateFrameworkRequest) async throws
      -> GoogleCloudSecurityComplianceV1.Framework

    /// See `ConfigClient.updateFramework`.
    func updateFramework(
      framework: Framework?,
      updateMask: GoogleCloudWKT.FieldMask?,
    ) async throws -> GoogleCloudSecurityComplianceV1.Framework

    /// See `ConfigClient.deleteFramework`.
    func deleteFramework(request: DeleteFrameworkRequest) async throws

    /// See `ConfigClient.deleteFramework`.
    func deleteFramework(
      name: Swift.String,
    ) async throws

    /// See `ConfigClient.listCloudControls`.
    func listCloudControls(request: ListCloudControlsRequest) async throws
      -> GoogleCloudSecurityComplianceV1.ListCloudControlsResponse

    /// See `ConfigClient.listCloudControls`.
    func listCloudControls(
      byItem: ListCloudControlsRequest
    ) throws -> any AsyncSequence<CloudControl, Swift.Error>

    /// See `ConfigClient.listCloudControls`.
    func listCloudControls(
      parent: Swift.String,
    ) throws -> any AsyncSequence<CloudControl, Swift.Error>

    /// See `ConfigClient.getCloudControl`.
    func getCloudControl(request: GetCloudControlRequest) async throws
      -> GoogleCloudSecurityComplianceV1.CloudControl

    /// See `ConfigClient.getCloudControl`.
    func getCloudControl(
      name: Swift.String,
    ) async throws -> GoogleCloudSecurityComplianceV1.CloudControl

    /// See `ConfigClient.createCloudControl`.
    func createCloudControl(request: CreateCloudControlRequest) async throws
      -> GoogleCloudSecurityComplianceV1.CloudControl

    /// See `ConfigClient.createCloudControl`.
    func createCloudControl(
      parent: Swift.String,
      cloudControl: CloudControl?,
      cloudControlId: Swift.String,
    ) async throws -> GoogleCloudSecurityComplianceV1.CloudControl

    /// See `ConfigClient.updateCloudControl`.
    func updateCloudControl(request: UpdateCloudControlRequest) async throws
      -> GoogleCloudSecurityComplianceV1.CloudControl

    /// See `ConfigClient.updateCloudControl`.
    func updateCloudControl(
      cloudControl: CloudControl?,
      updateMask: GoogleCloudWKT.FieldMask?,
    ) async throws -> GoogleCloudSecurityComplianceV1.CloudControl

    /// See `ConfigClient.deleteCloudControl`.
    func deleteCloudControl(request: DeleteCloudControlRequest) async throws

    /// See `ConfigClient.deleteCloudControl`.
    func deleteCloudControl(
      name: Swift.String,
    ) async throws

    /// See `ConfigClient.listLocations`.
    func listLocations(request: GoogleCloudLocation.ListLocationsRequest) async throws
      -> GoogleCloudLocation.ListLocationsResponse

    /// See `ConfigClient.listLocations`.
    func listLocations(
      byItem: GoogleCloudLocation.ListLocationsRequest
    ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error>

    /// See `ConfigClient.getLocation`.
    func getLocation(request: GoogleCloudLocation.GetLocationRequest) async throws
      -> GoogleCloudLocation.Location

    /// See `ConfigClient.listOperations`.
    func listOperations(request: GoogleLongRunning.ListOperationsRequest) async throws
      -> GoogleLongRunning.ListOperationsResponse

    /// See `ConfigClient.listOperations`.
    func listOperations(
      byItem: GoogleLongRunning.ListOperationsRequest
    ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error>

    /// See `ConfigClient.listOperations`.
    func listOperations(
      name: Swift.String,
      filter: Swift.String,
    ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error>

    /// See `ConfigClient.deleteOperation`.
    func deleteOperation(request: GoogleLongRunning.DeleteOperationRequest) async throws

    /// See `ConfigClient.deleteOperation`.
    func deleteOperation(
      name: Swift.String,
    ) async throws

    /// See `ConfigClient.cancelOperation`.
    func cancelOperation(request: GoogleLongRunning.CancelOperationRequest) async throws

    /// See `ConfigClient.cancelOperation`.
    func cancelOperation(
      name: Swift.String,
    ) async throws

    /// See `ConfigClient.listFrameworks`.
    func listFrameworks(
      request: ListFrameworksRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSecurityComplianceV1.ListFrameworksResponse

    /// See `ConfigClient.listFrameworks`.
    func listFrameworks(
      byItem: ListFrameworksRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<Framework, Swift.Error>

    /// See `ConfigClient.getFramework`.
    func getFramework(
      request: GetFrameworkRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSecurityComplianceV1.Framework

    /// See `ConfigClient.createFramework`.
    func createFramework(
      request: CreateFrameworkRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSecurityComplianceV1.Framework

    /// See `ConfigClient.updateFramework`.
    func updateFramework(
      request: UpdateFrameworkRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSecurityComplianceV1.Framework

    /// See `ConfigClient.deleteFramework`.
    func deleteFramework(
      request: DeleteFrameworkRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    /// See `ConfigClient.listCloudControls`.
    func listCloudControls(
      request: ListCloudControlsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSecurityComplianceV1.ListCloudControlsResponse

    /// See `ConfigClient.listCloudControls`.
    func listCloudControls(
      byItem: ListCloudControlsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<CloudControl, Swift.Error>

    /// See `ConfigClient.getCloudControl`.
    func getCloudControl(
      request: GetCloudControlRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSecurityComplianceV1.CloudControl

    /// See `ConfigClient.createCloudControl`.
    func createCloudControl(
      request: CreateCloudControlRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSecurityComplianceV1.CloudControl

    /// See `ConfigClient.updateCloudControl`.
    func updateCloudControl(
      request: UpdateCloudControlRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSecurityComplianceV1.CloudControl

    /// See `ConfigClient.deleteCloudControl`.
    func deleteCloudControl(
      request: DeleteCloudControlRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    /// See `ConfigClient.listLocations`.
    func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse

    /// See `ConfigClient.listLocations`.
    func listLocations(
      byItem: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error>

    /// See `ConfigClient.getLocation`.
    func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location

    /// See `ConfigClient.listOperations`.
    func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse

    /// See `ConfigClient.listOperations`.
    func listOperations(
      byItem: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error>

    /// See `ConfigClient.deleteOperation`.
    func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    /// See `ConfigClient.cancelOperation`.
    func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws
  }
}

// Default implementations
extension Clients.ConfigProtocol {
  public func listFrameworks(request: ListFrameworksRequest) async throws
    -> GoogleCloudSecurityComplianceV1.ListFrameworksResponse
  {
    try await self.listFrameworks(request: request, options: .init())
  }

  public func listFrameworks(
    request: ListFrameworksRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudSecurityComplianceV1.ListFrameworksResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listFrameworks(
    byItem: ListFrameworksRequest
  ) throws -> any AsyncSequence<Framework, Swift.Error> {
    try self.listFrameworks(byItem: byItem, options: .init())
  }

  public func listFrameworks(
    byItem: ListFrameworksRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Framework, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudSecurityComplianceV1.ListFrameworksResponse
      in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listFrameworks(
    parent: Swift.String,
  ) throws -> any AsyncSequence<Framework, Swift.Error> {
    let request = ListFrameworksRequest().with {
      $0.parent = parent
    }
    return try self.listFrameworks(byItem: request)
  }

  public func getFramework(request: GetFrameworkRequest) async throws
    -> GoogleCloudSecurityComplianceV1.Framework
  {
    try await self.getFramework(request: request, options: .init())
  }

  public func getFramework(
    request: GetFrameworkRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudSecurityComplianceV1.Framework {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getFramework(
    name: Swift.String,
  ) async throws -> GoogleCloudSecurityComplianceV1.Framework {
    let request = GetFrameworkRequest().with {
      $0.name = name
    }
    return try await self.getFramework(request: request)
  }

  public func createFramework(request: CreateFrameworkRequest) async throws
    -> GoogleCloudSecurityComplianceV1.Framework
  {
    try await self.createFramework(request: request, options: .init())
  }

  public func createFramework(
    request: CreateFrameworkRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudSecurityComplianceV1.Framework {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func createFramework(
    parent: Swift.String,
    framework: Framework?,
    frameworkId: Swift.String,
  ) async throws -> GoogleCloudSecurityComplianceV1.Framework {
    let request = CreateFrameworkRequest().with {
      $0.parent = parent
      $0.framework = framework
      $0.frameworkId = frameworkId
    }
    return try await self.createFramework(request: request)
  }

  public func updateFramework(request: UpdateFrameworkRequest) async throws
    -> GoogleCloudSecurityComplianceV1.Framework
  {
    try await self.updateFramework(request: request, options: .init())
  }

  public func updateFramework(
    request: UpdateFrameworkRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudSecurityComplianceV1.Framework {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func updateFramework(
    framework: Framework?,
    updateMask: GoogleCloudWKT.FieldMask?,
  ) async throws -> GoogleCloudSecurityComplianceV1.Framework {
    let request = UpdateFrameworkRequest().with {
      $0.framework = framework
      $0.updateMask = updateMask
    }
    return try await self.updateFramework(request: request)
  }

  public func deleteFramework(request: DeleteFrameworkRequest) async throws {
    try await self.deleteFramework(request: request, options: .init())
  }

  public func deleteFramework(
    request: DeleteFrameworkRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func deleteFramework(
    name: Swift.String,
  ) async throws {
    let request = DeleteFrameworkRequest().with {
      $0.name = name
    }
    try await self.deleteFramework(request: request)
  }

  public func listCloudControls(request: ListCloudControlsRequest) async throws
    -> GoogleCloudSecurityComplianceV1.ListCloudControlsResponse
  {
    try await self.listCloudControls(request: request, options: .init())
  }

  public func listCloudControls(
    request: ListCloudControlsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudSecurityComplianceV1.ListCloudControlsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listCloudControls(
    byItem: ListCloudControlsRequest
  ) throws -> any AsyncSequence<CloudControl, Swift.Error> {
    try self.listCloudControls(byItem: byItem, options: .init())
  }

  public func listCloudControls(
    byItem: ListCloudControlsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<CloudControl, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws
        -> GoogleCloudSecurityComplianceV1.ListCloudControlsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listCloudControls(
    parent: Swift.String,
  ) throws -> any AsyncSequence<CloudControl, Swift.Error> {
    let request = ListCloudControlsRequest().with {
      $0.parent = parent
    }
    return try self.listCloudControls(byItem: request)
  }

  public func getCloudControl(request: GetCloudControlRequest) async throws
    -> GoogleCloudSecurityComplianceV1.CloudControl
  {
    try await self.getCloudControl(request: request, options: .init())
  }

  public func getCloudControl(
    request: GetCloudControlRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudSecurityComplianceV1.CloudControl {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getCloudControl(
    name: Swift.String,
  ) async throws -> GoogleCloudSecurityComplianceV1.CloudControl {
    let request = GetCloudControlRequest().with {
      $0.name = name
    }
    return try await self.getCloudControl(request: request)
  }

  public func createCloudControl(request: CreateCloudControlRequest) async throws
    -> GoogleCloudSecurityComplianceV1.CloudControl
  {
    try await self.createCloudControl(request: request, options: .init())
  }

  public func createCloudControl(
    request: CreateCloudControlRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudSecurityComplianceV1.CloudControl {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func createCloudControl(
    parent: Swift.String,
    cloudControl: CloudControl?,
    cloudControlId: Swift.String,
  ) async throws -> GoogleCloudSecurityComplianceV1.CloudControl {
    let request = CreateCloudControlRequest().with {
      $0.parent = parent
      $0.cloudControl = cloudControl
      $0.cloudControlId = cloudControlId
    }
    return try await self.createCloudControl(request: request)
  }

  public func updateCloudControl(request: UpdateCloudControlRequest) async throws
    -> GoogleCloudSecurityComplianceV1.CloudControl
  {
    try await self.updateCloudControl(request: request, options: .init())
  }

  public func updateCloudControl(
    request: UpdateCloudControlRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudSecurityComplianceV1.CloudControl {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func updateCloudControl(
    cloudControl: CloudControl?,
    updateMask: GoogleCloudWKT.FieldMask?,
  ) async throws -> GoogleCloudSecurityComplianceV1.CloudControl {
    let request = UpdateCloudControlRequest().with {
      $0.cloudControl = cloudControl
      $0.updateMask = updateMask
    }
    return try await self.updateCloudControl(request: request)
  }

  public func deleteCloudControl(request: DeleteCloudControlRequest) async throws {
    try await self.deleteCloudControl(request: request, options: .init())
  }

  public func deleteCloudControl(
    request: DeleteCloudControlRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func deleteCloudControl(
    name: Swift.String,
  ) async throws {
    let request = DeleteCloudControlRequest().with {
      $0.name = name
    }
    try await self.deleteCloudControl(request: request)
  }

  public func listLocations(request: GoogleCloudLocation.ListLocationsRequest) async throws
    -> GoogleCloudLocation.ListLocationsResponse
  {
    try await self.listLocations(request: request, options: .init())
  }

  public func listLocations(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLocation.ListLocationsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listLocations(
    byItem: GoogleCloudLocation.ListLocationsRequest
  ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
    try self.listLocations(byItem: byItem, options: .init())
  }

  public func listLocations(
    byItem: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudLocation.ListLocationsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func getLocation(request: GoogleCloudLocation.GetLocationRequest) async throws
    -> GoogleCloudLocation.Location
  {
    try await self.getLocation(request: request, options: .init())
  }

  public func getLocation(
    request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLocation.Location {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listOperations(request: GoogleLongRunning.ListOperationsRequest) async throws
    -> GoogleLongRunning.ListOperationsResponse
  {
    try await self.listOperations(request: request, options: .init())
  }

  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listOperations(
    byItem: GoogleLongRunning.ListOperationsRequest
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    try self.listOperations(byItem: byItem, options: .init())
  }

  public func listOperations(
    byItem: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleLongRunning.ListOperationsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listOperations(
    name: Swift.String,
    filter: Swift.String,
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    let request = GoogleLongRunning.ListOperationsRequest().with {
      $0.name = name
      $0.filter = filter
    }
    return try self.listOperations(byItem: request)
  }

  public func getOperation(request: GoogleLongRunning.GetOperationRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.getOperation(request: request, options: .init())
  }

  public func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getOperation(
    name: Swift.String,
  ) async throws -> GoogleLongRunning.Operation {
    let request = GoogleLongRunning.GetOperationRequest().with {
      $0.name = name
    }
    return try await self.getOperation(request: request)
  }

  public func deleteOperation(request: GoogleLongRunning.DeleteOperationRequest) async throws {
    try await self.deleteOperation(request: request, options: .init())
  }

  public func deleteOperation(
    request: GoogleLongRunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func deleteOperation(
    name: Swift.String,
  ) async throws {
    let request = GoogleLongRunning.DeleteOperationRequest().with {
      $0.name = name
    }
    try await self.deleteOperation(request: request)
  }

  public func cancelOperation(request: GoogleLongRunning.CancelOperationRequest) async throws {
    try await self.cancelOperation(request: request, options: .init())
  }

  public func cancelOperation(
    request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func cancelOperation(
    name: Swift.String,
  ) async throws {
    let request = GoogleLongRunning.CancelOperationRequest().with {
      $0.name = name
    }
    try await self.cancelOperation(request: request)
  }
}
