// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudLocation
import GoogleCloudWkt
import GoogleLongRunning
import GoogleCloudGax
import struct Logging.Logger

extension Clients {
  final class ConfigLogging: ConfigStub {
    let inner: any ConfigStub
    let logger: Logger

    public init(_ inner: any ConfigStub, logger: Logger) {
      var logger = logger
      logger[metadataKey: "gcp.artifact.id"] = "google-cloud-cloudsecuritycompliance-v1"
      logger[metadataKey: "gcp.client.service"] = "cloudsecuritycompliance"
      logger[metadataKey: "gcp.experimental.swift.client"] = "Config"
      self.inner = inner
      self.logger = logger
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleCloudGax.RequestOptions,
      name: Swift.String,
      action: (Input, GoogleCloudGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      var logger = logger
      logger[metadataKey: "gcp.experimental.swift.request.id"] = "\(UUID())"
      logger[metadataKey: "gcp.experimental.swift.method"] = .string(name)
      logger.debug("enter  : \(request) \(options)")
      do {
        let output = try await action(request, options)
        logger.debug("success: \(request) \(options) \(output)")
        return output
      } catch let error {
        logger.debug("error  : \(request) \(options) \(error)")
        throw error
      }
    }

    public func listFrameworks(
      request: ListFrameworksRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSecurityComplianceV1.ListFrameworksResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listFrameworks",
        action: {
          (r: ListFrameworksRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudSecurityComplianceV1.ListFrameworksResponse
          in
          return try await self.inner.listFrameworks(request: r, options: o)
        })
    }

    public func getFramework(
      request: GetFrameworkRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSecurityComplianceV1.Framework {
      try await self._intercept(
        request: request,
        options: options,
        name: "getFramework",
        action: {
          (r: GetFrameworkRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudSecurityComplianceV1.Framework
          in
          return try await self.inner.getFramework(request: r, options: o)
        })
    }

    public func createFramework(
      request: CreateFrameworkRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSecurityComplianceV1.Framework {
      try await self._intercept(
        request: request,
        options: options,
        name: "createFramework",
        action: {
          (r: CreateFrameworkRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudSecurityComplianceV1.Framework
          in
          return try await self.inner.createFramework(request: r, options: o)
        })
    }

    public func updateFramework(
      request: UpdateFrameworkRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSecurityComplianceV1.Framework {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateFramework",
        action: {
          (r: UpdateFrameworkRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudSecurityComplianceV1.Framework
          in
          return try await self.inner.updateFramework(request: r, options: o)
        })
    }

    public func deleteFramework(
      request: DeleteFrameworkRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteFramework",
        action: {
          (r: DeleteFrameworkRequest, o: GoogleCloudGax.RequestOptions) async throws -> Void in
          return try await self.inner.deleteFramework(request: r, options: o)
        })
    }

    public func listCloudControls(
      request: ListCloudControlsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSecurityComplianceV1.ListCloudControlsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listCloudControls",
        action: {
          (r: ListCloudControlsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudSecurityComplianceV1.ListCloudControlsResponse
          in
          return try await self.inner.listCloudControls(request: r, options: o)
        })
    }

    public func getCloudControl(
      request: GetCloudControlRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSecurityComplianceV1.CloudControl {
      try await self._intercept(
        request: request,
        options: options,
        name: "getCloudControl",
        action: {
          (r: GetCloudControlRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudSecurityComplianceV1.CloudControl
          in
          return try await self.inner.getCloudControl(request: r, options: o)
        })
    }

    public func createCloudControl(
      request: CreateCloudControlRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSecurityComplianceV1.CloudControl {
      try await self._intercept(
        request: request,
        options: options,
        name: "createCloudControl",
        action: {
          (r: CreateCloudControlRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudSecurityComplianceV1.CloudControl
          in
          return try await self.inner.createCloudControl(request: r, options: o)
        })
    }

    public func updateCloudControl(
      request: UpdateCloudControlRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSecurityComplianceV1.CloudControl {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateCloudControl",
        action: {
          (r: UpdateCloudControlRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudSecurityComplianceV1.CloudControl
          in
          return try await self.inner.updateCloudControl(request: r, options: o)
        })
    }

    public func deleteCloudControl(
      request: DeleteCloudControlRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteCloudControl",
        action: {
          (r: DeleteCloudControlRequest, o: GoogleCloudGax.RequestOptions) async throws -> Void in
          return try await self.inner.deleteCloudControl(request: r, options: o)
        })
    }

    public func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listLocations",
        action: {
          (r: GoogleCloudLocation.ListLocationsRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> GoogleCloudLocation.ListLocationsResponse
          in
          return try await self.inner.listLocations(request: r, options: o)
        })
    }

    public func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location {
      try await self._intercept(
        request: request,
        options: options,
        name: "getLocation",
        action: {
          (r: GoogleCloudLocation.GetLocationRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudLocation.Location
          in
          return try await self.inner.getLocation(request: r, options: o)
        })
    }

    public func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listOperations",
        action: {
          (r: GoogleLongRunning.ListOperationsRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> GoogleLongRunning.ListOperationsResponse
          in
          return try await self.inner.listOperations(request: r, options: o)
        })
    }

    public func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "getOperation",
        action: {
          (r: GoogleLongRunning.GetOperationRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.getOperation(request: r, options: o)
        })
    }

    public func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteOperation",
        action: {
          (r: GoogleLongRunning.DeleteOperationRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> Void in
          return try await self.inner.deleteOperation(request: r, options: o)
        })
    }

    public func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "cancelOperation",
        action: {
          (r: GoogleLongRunning.CancelOperationRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> Void in
          return try await self.inner.cancelOperation(request: r, options: o)
        })
    }
  }
}
