// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// The details for control compliance.
public struct ControlComplianceSummary: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The name of the control.
  public var control: Swift.String = Swift.String()

  /// The display name of the control.
  public var displayName: Swift.String = Swift.String()

  /// The description of the control.
  public var description: Swift.String = Swift.String()

  /// Output only. The overall evaluation status of the control.
  public var overallEvaluationState: EvaluationState = EvaluationState()

  /// The total number of findings for the control.
  public var totalFindingsCount: Swift.Int32 = Swift.Int32()

  /// The list of compliance frameworks that the control belongs to.
  public var complianceFrameworks: [Swift.String] = []

  /// The list of similar controls.
  public var similarControls: [SimilarControls] = []

  /// The list of cloud control reports.
  public var cloudControlReports: [CloudControlReport] = []

  /// The responsibility type for the control.
  public var controlResponsibilityType: RegulatoryControlResponsibilityType =
    RegulatoryControlResponsibilityType()

  /// Whether the control is a fake control. Fake controls are created
  /// and mapped to cloud controls that don't belong to a control group.
  public var isFakeControl: Swift.Bool = Swift.Bool()

  /// Identifier. The name of the control compliance summary.
  public var name: Swift.String = Swift.String()

  /// Initialize a new instance of `ControlComplianceSummary`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ControlComplianceSummary().with { $0.control = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.cloudsecuritycompliance.v1.ControlComplianceSummary"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
