// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// The request message for [CreateFrameworkAudit][].
public struct CreateFrameworkAuditRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The parent resource where this framework audit is created.
  ///
  /// Supported formats are the following:
  ///
  /// * `organizations/{organization_id}/locations/{location}`
  /// * `folders/{folder_id}/locations/{location}`
  /// * `projects/{project_id}/locations/{location}`
  public var parent: Swift.String = Swift.String()

  /// Optional. The ID to use for the framework audit. The ID becomes the final
  /// component of the framework audit's full resource name.
  ///
  /// The ID must be between 4-63 characters, and valid characters
  /// are `\[a-z][0-9]-\`.
  public var frameworkAuditId: Swift.String = Swift.String()

  /// Required. The framework audit to create.
  public var frameworkAudit: FrameworkAudit? = nil

  /// Initialize a new instance of `CreateFrameworkAuditRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CreateFrameworkAuditRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.cloudsecuritycompliance.v1.CreateFrameworkAuditRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
