// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation

/// The state of the deployment resource.
public enum DeploymentState: Codable, Equatable, Sendable {
  /// Default value. This value is unused.
  case unspecified
  /// Validating the deployment.
  case validating
  /// Deployment is being created.
  case creating
  /// Deployment is being deleted.
  case deleting
  /// Deployment has failed. All the changes made by the deployment were
  /// successfully rolled back. You can retry or delete a deployment that's
  /// in this state.
  case failed
  /// Deployment is successful and ready to use.
  case ready
  /// Deployment is partially deployed. All the cloud controls weren't deployed
  /// successfully. Retrying the operation resumes from the first failed
  /// step.
  case partiallyDeployed
  /// Deployment is partially deleted. All the cloud control deployments weren't
  /// deleted successfully. Retrying the operation resumes from the first
  /// failed step.
  case partiallyDeleted
  /// Deployment is being updated.
  case updating
  /// Encodes an unknown integer value.
  ///
  /// The most common cause for an unknown values is for the service to send
  /// a value unknown to the library. We recommend you update your library to
  /// the latest version.
  case unknownIntValue(Int)
  /// Encodes an unknown string value.
  ///
  /// The most common cause for an unknown values is for the service to send
  /// a value unknown to the library. We recommend you update your library to
  /// the latest version.
  case unknownStringValue(String)

  public init() {
    self = .unspecified
  }

  /// Returns the integer value associated with the enumeration.
  ///
  /// If the enumeration was initialized with an unknown string value, this returns `nil`.
  public var intValue: Int? {
    switch self {
    case .unspecified: return 0
    case .validating: return 1
    case .creating: return 2
    case .deleting: return 3
    case .failed: return 4
    case .ready: return 5
    case .partiallyDeployed: return 6
    case .partiallyDeleted: return 7
    case .updating: return 8
    case .unknownIntValue(let v): return v
    case .unknownStringValue: return nil
    }
  }

  /// Returns the string value (or name) associated with the enumeration.
  ///
  /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
  public var stringValue: Swift.String? {
    switch self {
    case .unspecified: return "DEPLOYMENT_STATE_UNSPECIFIED"
    case .validating: return "DEPLOYMENT_STATE_VALIDATING"
    case .creating: return "DEPLOYMENT_STATE_CREATING"
    case .deleting: return "DEPLOYMENT_STATE_DELETING"
    case .failed: return "DEPLOYMENT_STATE_FAILED"
    case .ready: return "DEPLOYMENT_STATE_READY"
    case .partiallyDeployed: return "DEPLOYMENT_STATE_PARTIALLY_DEPLOYED"
    case .partiallyDeleted: return "DEPLOYMENT_STATE_PARTIALLY_DELETED"
    case .updating: return "DEPLOYMENT_STATE_UPDATING"
    case .unknownIntValue: return nil
    case .unknownStringValue(let v): return v
    }
  }

  /// Initialize from a string value.
  ///
  /// If the value is unknown, this initializes to [`unknownStringValue`](doc:DeploymentState/unknownStringValue(_:)).
  public init(stringValue: Swift.String) {
    switch stringValue {
    case "DEPLOYMENT_STATE_UNSPECIFIED": self = .unspecified
    case "DEPLOYMENT_STATE_VALIDATING": self = .validating
    case "DEPLOYMENT_STATE_CREATING": self = .creating
    case "DEPLOYMENT_STATE_DELETING": self = .deleting
    case "DEPLOYMENT_STATE_UPDATING": self = .updating
    case "DEPLOYMENT_STATE_FAILED": self = .failed
    case "DEPLOYMENT_STATE_READY": self = .ready
    case "DEPLOYMENT_STATE_PARTIALLY_DEPLOYED": self = .partiallyDeployed
    case "DEPLOYMENT_STATE_PARTIALLY_DELETED": self = .partiallyDeleted
    default: self = .unknownStringValue(stringValue)
    }
  }

  /// Initialize from an integer value.
  ///
  /// If the value is unknown, this initializes to [`unknownIntValue`](doc:DeploymentState/unknownIntValue(_:)).
  public init(intValue: Int) {
    switch intValue {
    case 0: self = .unspecified
    case 1: self = .validating
    case 2: self = .creating
    case 3: self = .deleting
    case 4: self = .failed
    case 5: self = .ready
    case 6: self = .partiallyDeployed
    case 7: self = .partiallyDeleted
    case 8: self = .updating
    default: self = .unknownIntValue(intValue)
    }
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.singleValueContainer()
    if let v = try? container.decode(Int.self) {
      self.init(intValue: v)
      return
    }
    if let s = try? container.decode(String.self) {
      if let v = Int(s) {
        self.init(intValue: v)
      } else {
        self.init(stringValue: s)
      }
      return
    }
    throw DecodingError.dataCorruptedError(
      in: container, debugDescription: "Expected enum value, must be integer or string.")
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.singleValueContainer()
    switch self {
    case .unspecified: return try container.encode(0)
    case .validating: return try container.encode(1)
    case .creating: return try container.encode(2)
    case .deleting: return try container.encode(3)
    case .failed: return try container.encode(4)
    case .ready: return try container.encode(5)
    case .partiallyDeployed: return try container.encode(6)
    case .partiallyDeleted: return try container.encode(7)
    case .updating: return try container.encode(8)
    case .unknownIntValue(let v): return try container.encode(v)
    case .unknownStringValue(let v): return try container.encode(v)
    }
  }
}
