// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// The details for a finding.
public struct FindingSummary: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The category of the finding.
  public var findingCategory: Swift.String = Swift.String()

  /// The class of the finding.
  public var findingClass: FindingClass = FindingClass()

  /// The severity of the finding.
  public var severity: Severity = Severity()

  /// The count of the finding.
  public var findingCount: Swift.Int64 = Swift.Int64()

  /// Output only. The last updated time of the finding.
  public var updateTime: GoogleCloudWkt.Timestamp? = nil

  /// Optional. The list of compliance frameworks that the finding belongs to.
  public var relatedFrameworks: [Swift.String] = []

  /// Identifier. The name of the finding summary.
  public var name: Swift.String = Swift.String()

  /// Initialize a new instance of `FindingSummary`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = FindingSummary().with { $0.findingCategory = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.cloudsecuritycompliance.v1.FindingSummary"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
