// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// The reference to a framework deployment.
public struct FrameworkDeploymentReference: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Output only. The name of the framework deployment, in the format
  /// `organizations/{organization}/locations/{location}/frameworkDeployments/{framework_deployment}`
  /// or
  /// `projects/{project}/locations/{location}/frameworkDeployments/{framework_deployment}`.
  /// The only supported location is `global`.
  public var frameworkDeployment: Swift.String = Swift.String()

  /// Optional. The reference to the framework that this deployment is for.
  /// For example:
  ///
  /// ```
  /// {
  ///   framework:
  ///   "organizations/{organization}/locations/{location}/frameworks/{framework}",
  ///   major_revision_id: 1
  /// }
  /// ```
  ///
  /// The only supported location is `global`.
  public var frameworkReference: FrameworkReference? = nil

  /// Optional. The display name of the framework that this framework deployment
  /// is for.
  public var frameworkDisplayName: Swift.String = Swift.String()

  /// Initialize a new instance of `FrameworkDeploymentReference`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = FrameworkDeploymentReference().with { $0.frameworkDeployment = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return
      "type.googleapis.com/google.cloud.cloudsecuritycompliance.v1.FrameworkDeploymentReference"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
