// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// A destination for the framework audit.
public struct FrameworkAuditDestination: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The type of destination.
  public var destinationType: OneOf_DestinationType? = nil

  /// Initialize a new instance of `FrameworkAuditDestination`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = FrameworkAuditDestination().with { $0.bucket = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case bucket = "bucket"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)

    var destinationType: OneOf_DestinationType? = nil
    let destinationTypeCheckAndSet = {
      if destinationType != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'destinationType'"))
      }
      destinationType = $0
    }
    if let bucket = try container.decodeIfPresent(BucketDestination?.self, forKey: .bucket) {
      try destinationTypeCheckAndSet(.bucket(bucket))
    }
    self.destinationType = destinationType
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)

    if let choice = self.destinationType {
      switch choice {
      case .bucket(let value):
        try container.encode(value, forKey: .bucket)
      }
    }
  }

  /// The type of destination.
  public enum OneOf_DestinationType: Codable, Equatable, Sendable {
    /// The Cloud Storage bucket destination.
    indirect case bucket(BucketDestination?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.cloudsecuritycompliance.v1.FrameworkAuditDestination"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
