// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// The reference of a framework, in one of the following formats:
/// - `organizations/{organization}/locations/{location}/frameworks/{framework}`
/// - `projects/{project}/locations/{location}/frameworks/{framework}`.
///
/// The only supported location is `global`.
public struct FrameworkReference: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The major version of the framework. If not specified, the version
  /// corresponds to the latest version of the framework.
  public var framework: Swift.String = Swift.String()

  /// Optional. The major version of the framework. If not specified, the version
  /// corresponds to the latest version of the framework.
  public var majorRevisionId: Swift.Int64? = nil

  /// Initialize a new instance of `FrameworkReference`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = FrameworkReference().with { $0.framework = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.cloudsecuritycompliance.v1.FrameworkReference"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
