// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// The response message for [GetFrameworkComplianceReport][].
public struct FrameworkComplianceReport: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The name of the framework.
  public var framework: Swift.String = Swift.String()

  /// The description of the framework.
  public var frameworkDescription: Swift.String = Swift.String()

  /// Output only. The last updated time of the report.
  public var updateTime: GoogleCloudWkt.Timestamp? = nil

  /// The control assessment details of the framework.
  public var controlAssessmentDetails: ControlAssessmentDetails? = nil

  /// The type of framework.
  public var frameworkType: Framework.FrameworkType = Framework.FrameworkType()

  /// The list of cloud providers supported by the framework.
  public var supportedCloudProviders: [CloudProvider] = []

  /// The list of framework categories supported.
  public var frameworkCategories: [FrameworkCategory] = []

  /// Optional. The display name for the framework.
  public var frameworkDisplayName: Swift.String = Swift.String()

  /// Identifier. The name of the framework compliance report.
  public var name: Swift.String = Swift.String()

  /// The latest major revision ID of the framework.
  public var majorRevisionId: Swift.Int64 = Swift.Int64()

  /// The latest minor revision ID of the latest major revision of the framework.
  public var minorRevisionId: Swift.Int64 = Swift.Int64()

  /// The target resource details of the framework.
  public var targetResourceDetails: [TargetResourceDetails] = []

  /// Initialize a new instance of `FrameworkComplianceReport`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = FrameworkComplianceReport().with { $0.framework = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.cloudsecuritycompliance.v1.FrameworkComplianceReport"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
