// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// A framework audit.
public struct FrameworkAudit: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Output only. Identifier. The name of the framework audit.
  public var name: Swift.String = Swift.String()

  /// Output only. The ID of the framework audit.
  public var frameworkAuditId: Swift.String = Swift.String()

  /// Output only. The compliance framework used for the audit.
  public var complianceFramework: Swift.String = Swift.String()

  /// Output only. The scope of the audit.
  public var scope: Swift.String = Swift.String()

  /// Required. The destination for the audit reports.
  public var frameworkAuditDestination: FrameworkAuditDestination? = nil

  /// Output only. The time that the audit started.
  public var startTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. The time that the audit finished.
  public var finishTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. The overall compliance state of the audit.
  public var complianceState: ComplianceState = ComplianceState()

  /// Output only. The summary of the report.
  public var reportSummary: ReportSummary? = nil

  /// Optional. The details for the cloud control groups within this audit.
  public var cloudControlGroupAuditDetails: [CloudControlGroupAuditDetails] = []

  /// Optional. The details for the cloud controls within this audit.
  public var cloudControlAuditDetails: [CloudControlAuditDetails] = []

  /// Output only. The ID of the long-running operation.
  public var operationId: Swift.String = Swift.String()

  /// Output only. The framework audit state of the audit.
  public var state: FrameworkAudit.State = FrameworkAudit.State()

  /// Initialize a new instance of `FrameworkAudit`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = FrameworkAudit().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// The state of the framework audit.
  public enum State: Codable, Equatable, Sendable {
    /// Default value. This value is unused.
    case unspecified
    /// The audit is scheduled.
    case scheduled
    /// The audit is running.
    case running
    /// The audit results are being uploaded.
    case uploading
    /// The audit failed.
    case failed
    /// The audit completed successfully.
    case succeeded
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .scheduled: return 1
      case .running: return 2
      case .uploading: return 3
      case .failed: return 4
      case .succeeded: return 5
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STATE_UNSPECIFIED"
      case .scheduled: return "SCHEDULED"
      case .running: return "RUNNING"
      case .uploading: return "UPLOADING"
      case .failed: return "FAILED"
      case .succeeded: return "SUCCEEDED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STATE_UNSPECIFIED": self = .unspecified
      case "SCHEDULED": self = .scheduled
      case "RUNNING": self = .running
      case "UPLOADING": self = .uploading
      case "FAILED": self = .failed
      case "SUCCEEDED": self = .succeeded
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .scheduled
      case 2: self = .running
      case 3: self = .uploading
      case 4: self = .failed
      case 5: self = .succeeded
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .scheduled: return try container.encode(1)
      case .running: return try container.encode(2)
      case .uploading: return try container.encode(3)
      case .failed: return try container.encode(4)
      case .succeeded: return try container.encode(5)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.cloudsecuritycompliance.v1.FrameworkAudit"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
