// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// The request message for [ListCloudControlDeployments][].
public struct ListCloudControlDeploymentsRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The parent resource for the cloud control deployment, in the
  /// format `organizations/{organization}/locations/{location}` or
  /// `projects/{project}/locations/{location}`.
  /// The only supported location is `global`.
  public var parent: Swift.String = Swift.String()

  /// Optional. The requested page size. The server might return fewer items than
  /// you requested.
  /// If unspecified, the server picks an appropriate default.
  public var pageSize: Swift.Int32 = Swift.Int32()

  /// Optional. A token that identifies the page of results that the server
  /// should return.
  public var pageToken: Swift.String = Swift.String()

  /// Optional. The filter to apply on the resource, as defined by
  /// [AIP-160: Filtering](https://google.aip.dev/160).
  public var filter: Swift.String = Swift.String()

  /// Optional. The sort order for the results. The following values are
  /// supported:
  ///
  /// * `name`
  /// * `name desc`
  ///
  /// If you do not specify a value, then the results are not sorted.
  public var orderBy: Swift.String = Swift.String()

  /// Initialize a new instance of `ListCloudControlDeploymentsRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ListCloudControlDeploymentsRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return
      "type.googleapis.com/google.cloud.cloudsecuritycompliance.v1.ListCloudControlDeploymentsRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
