// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Request message for [ListCloudControls][].
public struct ListCloudControlsRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The parent resource name, in one of the following formats:
  /// - `organizations/{organization}/locations/{location}`
  /// - `projects/{project}/locations/{location}`.
  ///
  /// The only supported location is `global`.
  public var parent: Swift.String = Swift.String()

  /// Optional. The maximum number of cloud controls to return. The default value
  /// is `500`.
  ///
  /// If you exceed the maximum value of `1000`, then the service uses the
  /// maximum value.
  public var pageSize: Swift.Int32 = Swift.Int32()

  /// Optional. A pagination token that's returned from a previous request to
  /// list cloud controls. Provide this token to retrieve the next page of
  /// results.
  ///
  /// When paginating, the parent that you provide to the
  /// [ListCloudControls][google.cloud.cloudsecuritycompliance.v1.Config.ListCloudControls]
  /// request must match the call that provided the page token.
  ///
  /// [google.cloud.cloudsecuritycompliance.v1.Config.ListCloudControls]: <doc:ConfigClient/listCloudControls(request:)>
  public var pageToken: Swift.String = Swift.String()

  /// Initialize a new instance of `ListCloudControlsRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ListCloudControlsRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.cloudsecuritycompliance.v1.ListCloudControlsRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
