// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// The request message for [ListFrameworkAudits][].
public struct ListFrameworkAuditsRequest: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Required. The parent resource where the framework audits are listed.
  ///
  /// Supported formats are the following:
  ///
  /// * `organizations/{organization_id}/locations/{location}`
  /// * `folders/{folder_id}/locations/{location}`
  /// * `projects/{project_id}/locations/{location}`
  public var parent: Swift.String = Swift.String()

  /// Optional. The maximum number of framework audits to return. The service
  /// might return fewer audits than this value. If unspecified, a maximum of 10
  /// framework audits are returned. The maximum value is 50; values above 50 are
  /// limited to 50.
  public var pageSize: Swift.Int32 = Swift.Int32()

  /// Optional. The `next_page_token` value that's returned from a previous list
  /// request, if any.
  public var pageToken: Swift.String = Swift.String()

  /// Optional. The filters to apply to the framework audits.
  /// Supported filters are `compliance_framework`, `compliance_state`,
  /// `create_time,` and `framework_audit_name`. If the filter is invalid, an
  /// invalid argument error is returned.
  /// For syntax details, see [AIP-160][https://google.aip.dev/160].
  public var filter: Swift.String = Swift.String()

  /// Initialize a new instance of `ListFrameworkAuditsRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ListFrameworkAuditsRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.cloudsecuritycompliance.v1.ListFrameworkAuditsRequest"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
