// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudLocation
import GoogleCloudWkt
import GoogleLongRunning
import GoogleCloudGax
import struct Logging.Logger

extension Clients {
  final class MonitoringLogging: MonitoringStub {
    let inner: any MonitoringStub
    let logger: Logger

    public init(_ inner: any MonitoringStub, logger: Logger) {
      var logger = logger
      logger[metadataKey: "gcp.artifact.id"] = "google-cloud-cloudsecuritycompliance-v1"
      logger[metadataKey: "gcp.client.service"] = "cloudsecuritycompliance"
      logger[metadataKey: "gcp.experimental.swift.client"] = "Monitoring"
      self.inner = inner
      self.logger = logger
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleCloudGax.RequestOptions,
      name: Swift.String,
      action: (Input, GoogleCloudGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      var logger = logger
      logger[metadataKey: "gcp.experimental.swift.request.id"] = "\(UUID())"
      logger[metadataKey: "gcp.experimental.swift.method"] = .string(name)
      logger.debug("enter  : \(request) \(options)")
      do {
        let output = try await action(request, options)
        logger.debug("success: \(request) \(options) \(output)")
        return output
      } catch let error {
        logger.debug("error  : \(request) \(options) \(error)")
        throw error
      }
    }

    public func listFrameworkComplianceSummaries(
      request: ListFrameworkComplianceSummariesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSecurityComplianceV1.ListFrameworkComplianceSummariesResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listFrameworkComplianceSummaries",
        action: {
          (r: ListFrameworkComplianceSummariesRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> GoogleCloudSecurityComplianceV1.ListFrameworkComplianceSummariesResponse
          in
          return try await self.inner.listFrameworkComplianceSummaries(request: r, options: o)
        })
    }

    public func listFindingSummaries(
      request: ListFindingSummariesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSecurityComplianceV1.ListFindingSummariesResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listFindingSummaries",
        action: {
          (r: ListFindingSummariesRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudSecurityComplianceV1.ListFindingSummariesResponse
          in
          return try await self.inner.listFindingSummaries(request: r, options: o)
        })
    }

    public func fetchFrameworkComplianceReport(
      request: FetchFrameworkComplianceReportRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSecurityComplianceV1.FrameworkComplianceReport {
      try await self._intercept(
        request: request,
        options: options,
        name: "fetchFrameworkComplianceReport",
        action: {
          (r: FetchFrameworkComplianceReportRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudSecurityComplianceV1.FrameworkComplianceReport
          in
          return try await self.inner.fetchFrameworkComplianceReport(request: r, options: o)
        })
    }

    public func listControlComplianceSummaries(
      request: ListControlComplianceSummariesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSecurityComplianceV1.ListControlComplianceSummariesResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listControlComplianceSummaries",
        action: {
          (r: ListControlComplianceSummariesRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudSecurityComplianceV1.ListControlComplianceSummariesResponse
          in
          return try await self.inner.listControlComplianceSummaries(request: r, options: o)
        })
    }

    public func aggregateFrameworkComplianceReport(
      request: AggregateFrameworkComplianceReportRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSecurityComplianceV1.AggregateFrameworkComplianceReportResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "aggregateFrameworkComplianceReport",
        action: {
          (r: AggregateFrameworkComplianceReportRequest, o: GoogleCloudGax.RequestOptions)
            async throws
            -> GoogleCloudSecurityComplianceV1.AggregateFrameworkComplianceReportResponse
          in
          return try await self.inner.aggregateFrameworkComplianceReport(request: r, options: o)
        })
    }

    public func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listLocations",
        action: {
          (r: GoogleCloudLocation.ListLocationsRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> GoogleCloudLocation.ListLocationsResponse
          in
          return try await self.inner.listLocations(request: r, options: o)
        })
    }

    public func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location {
      try await self._intercept(
        request: request,
        options: options,
        name: "getLocation",
        action: {
          (r: GoogleCloudLocation.GetLocationRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudLocation.Location
          in
          return try await self.inner.getLocation(request: r, options: o)
        })
    }

    public func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listOperations",
        action: {
          (r: GoogleLongRunning.ListOperationsRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> GoogleLongRunning.ListOperationsResponse
          in
          return try await self.inner.listOperations(request: r, options: o)
        })
    }

    public func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "getOperation",
        action: {
          (r: GoogleLongRunning.GetOperationRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.getOperation(request: r, options: o)
        })
    }

    public func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteOperation",
        action: {
          (r: GoogleLongRunning.DeleteOperationRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> Void in
          return try await self.inner.deleteOperation(request: r, options: o)
        })
    }

    public func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "cancelOperation",
        action: {
          (r: GoogleLongRunning.CancelOperationRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> Void in
          return try await self.inner.cancelOperation(request: r, options: o)
        })
    }
  }
}
