// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// The parameter substitution rules.
public struct ParameterSubstitutionRule: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The type of substitution.
  public var substitutionType: OneOf_SubstitutionType? = nil

  /// Initialize a new instance of `ParameterSubstitutionRule`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ParameterSubstitutionRule().with { $0.placeholderSubstitutionRule = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case placeholderSubstitutionRule = "placeholderSubstitutionRule"
    case attributeSubstitutionRule = "attributeSubstitutionRule"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)

    var substitutionType: OneOf_SubstitutionType? = nil
    let substitutionTypeCheckAndSet = {
      if substitutionType != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'substitutionType'"))
      }
      substitutionType = $0
    }
    if let placeholderSubstitutionRule = try container.decodeIfPresent(
      PlaceholderSubstitutionRule?.self, forKey: .placeholderSubstitutionRule)
    {
      try substitutionTypeCheckAndSet(.placeholderSubstitutionRule(placeholderSubstitutionRule))
    }
    if let attributeSubstitutionRule = try container.decodeIfPresent(
      AttributeSubstitutionRule?.self, forKey: .attributeSubstitutionRule)
    {
      try substitutionTypeCheckAndSet(.attributeSubstitutionRule(attributeSubstitutionRule))
    }
    self.substitutionType = substitutionType
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)

    if let choice = self.substitutionType {
      switch choice {
      case .placeholderSubstitutionRule(let value):
        try container.encode(value, forKey: .placeholderSubstitutionRule)
      case .attributeSubstitutionRule(let value):
        try container.encode(value, forKey: .attributeSubstitutionRule)
      }
    }
  }

  /// The type of substitution.
  public enum OneOf_SubstitutionType: Codable, Equatable, Sendable {
    /// The placeholder substitution rule.
    indirect case placeholderSubstitutionRule(PlaceholderSubstitutionRule?)
    /// The attribute substitution rule.
    indirect case attributeSubstitutionRule(AttributeSubstitutionRule?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.cloudsecuritycompliance.v1.ParameterSubstitutionRule"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
