// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// The parameter specification for the cloud control.
public struct ParameterSpec: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The name of the parameter.
  public var name: Swift.String = Swift.String()

  /// Optional. The friendly name of the parameter. The maximum length is 200
  /// characters.
  public var displayName: Swift.String = Swift.String()

  /// Optional. The description of the parameter. The maximum length is 2000
  /// characters.
  public var description: Swift.String = Swift.String()

  /// Required. Whether the parameter is required.
  public var isRequired: Swift.Bool = Swift.Bool()

  /// Required. The parameter value type.
  public var valueType: ParameterSpec.ValueType = ParameterSpec.ValueType()

  /// Optional. The default value of the parameter.
  public var defaultValue: ParamValue? = nil

  /// Optional. The list of parameter substitutions.
  public var substitutionRules: [ParameterSubstitutionRule] = []

  /// Optional. The parameter specification for `oneOf` attributes.
  public var subParameters: [ParameterSpec] = []

  /// Optional. The permitted set of values for the parameter.
  public var validation: Validation? = nil

  /// Initialize a new instance of `ParameterSpec`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ParameterSpec().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// The type of parameter value.
  public enum ValueType: Codable, Equatable, Sendable {
    /// Default value. This value is unused.
    case unspecified
    /// A string value.
    case string
    /// A boolean value.
    case boolean
    /// A string list value.
    case stringlist
    /// A numeric value.
    case number
    /// A oneOf value.
    case oneof
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .string: return 3
      case .boolean: return 4
      case .stringlist: return 5
      case .number: return 6
      case .oneof: return 7
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "VALUE_TYPE_UNSPECIFIED"
      case .string: return "STRING"
      case .boolean: return "BOOLEAN"
      case .stringlist: return "STRINGLIST"
      case .number: return "NUMBER"
      case .oneof: return "ONEOF"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:ValueType/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "VALUE_TYPE_UNSPECIFIED": self = .unspecified
      case "STRING": self = .string
      case "BOOLEAN": self = .boolean
      case "STRINGLIST": self = .stringlist
      case "NUMBER": self = .number
      case "ONEOF": self = .oneof
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:ValueType/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 3: self = .string
      case 4: self = .boolean
      case 5: self = .stringlist
      case 6: self = .number
      case 7: self = .oneof
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .string: return try container.encode(3)
      case .boolean: return try container.encode(4)
      case .stringlist: return try container.encode(5)
      case .number: return try container.encode(6)
      case .oneof: return try container.encode(7)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.cloudsecuritycompliance.v1.ParameterSpec"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
