// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// The possible parameter value types.
public struct ParamValue: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The list of possible parameter value types.
  public var kind: OneOf_Kind? = nil

  /// Initialize a new instance of `ParamValue`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ParamValue().with { $0.stringValue = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case stringValue = "stringValue"
    case boolValue = "boolValue"
    case stringListValue = "stringListValue"
    case numberValue = "numberValue"
    case oneofValue = "oneofValue"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)

    var kind: OneOf_Kind? = nil
    let kindCheckAndSet = {
      if kind != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath, debugDescription: "Multiple values set for oneof 'kind'"
          ))
      }
      kind = $0
    }
    if let stringValue = try container.decodeIfPresent(Swift.String.self, forKey: .stringValue) {
      try kindCheckAndSet(.stringValue(stringValue))
    }
    if let boolValue = try container.decodeIfPresent(Swift.Bool.self, forKey: .boolValue) {
      try kindCheckAndSet(.boolValue(boolValue))
    }
    if let stringListValue = try container.decodeIfPresent(
      StringList?.self, forKey: .stringListValue)
    {
      try kindCheckAndSet(.stringListValue(stringListValue))
    }
    if let numberValue = try container.decodeIfPresent(Swift.Double.self, forKey: .numberValue) {
      try kindCheckAndSet(.numberValue(numberValue))
    }
    if let oneofValue = try container.decodeIfPresent(Parameter?.self, forKey: .oneofValue) {
      try kindCheckAndSet(.oneofValue(oneofValue))
    }
    self.kind = kind
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)

    if let choice = self.kind {
      switch choice {
      case .stringValue(let value):
        try container.encode(value, forKey: .stringValue)
      case .boolValue(let value):
        try container.encode(value, forKey: .boolValue)
      case .stringListValue(let value):
        try container.encode(value, forKey: .stringListValue)
      case .numberValue(let value):
        try container.encode(value, forKey: .numberValue)
      case .oneofValue(let value):
        try container.encode(value, forKey: .oneofValue)
      }
    }
  }

  /// The list of possible parameter value types.
  public enum OneOf_Kind: Codable, Equatable, Sendable {
    /// Optional. A string value.
    case stringValue(Swift.String)
    /// Optional. A boolean value.
    case boolValue(Swift.Bool)
    /// Optional. A repeated string.
    indirect case stringListValue(StringList?)
    /// Optional. A double value.
    case numberValue(Swift.Double)
    /// Optional. Sub-parameter values.
    indirect case oneofValue(Parameter?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.cloudsecuritycompliance.v1.ParamValue"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
