// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// A rule in the cloud control.
public struct Rule: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Optional. The rule description. The maximum length is 2000 characters.
  public var description: Swift.String = Swift.String()

  /// Required. The functionality that's enabled by the rule.
  public var ruleActionTypes: [RuleActionType] = []

  /// The rule implementation.
  public var implementation: OneOf_Implementation? = nil

  /// Initialize a new instance of `Rule`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Rule().with { $0.celExpression = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case celExpression = "celExpression"
    case description = "description"
    case ruleActionTypes = "ruleActionTypes"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.description = try container.decode(Swift.String.self, forKey: .description)
    self.ruleActionTypes = try container.decode([RuleActionType].self, forKey: .ruleActionTypes)

    var implementation: OneOf_Implementation? = nil
    let implementationCheckAndSet = {
      if implementation != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'implementation'"))
      }
      implementation = $0
    }
    if let celExpression = try container.decodeIfPresent(
      CELExpression?.self, forKey: .celExpression)
    {
      try implementationCheckAndSet(.celExpression(celExpression))
    }
    self.implementation = implementation
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.description, forKey: .description)
    try container.encode(self.ruleActionTypes, forKey: .ruleActionTypes)

    if let choice = self.implementation {
      switch choice {
      case .celExpression(let value):
        try container.encode(value, forKey: .celExpression)
      }
    }
  }

  /// The rule implementation.
  public enum OneOf_Implementation: Codable, Equatable, Sendable {
    /// The rule's logic expression in Common Expression Language (CEL).
    indirect case celExpression(CELExpression?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.cloudsecuritycompliance.v1.Rule"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
