// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// The name of the target resource or the configuration that's required to
/// create a new target resource.
public struct TargetResourceConfig: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// The resource configuration for the target resource.
  public var resourceConfig: OneOf_ResourceConfig? = nil

  /// Initialize a new instance of `TargetResourceConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = TargetResourceConfig().with { $0.existingTargetResource = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case existingTargetResource = "existingTargetResource"
    case targetResourceCreationConfig = "targetResourceCreationConfig"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)

    var resourceConfig: OneOf_ResourceConfig? = nil
    let resourceConfigCheckAndSet = {
      if resourceConfig != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'resourceConfig'"))
      }
      resourceConfig = $0
    }
    if let existingTargetResource = try container.decodeIfPresent(
      Swift.String.self, forKey: .existingTargetResource)
    {
      try resourceConfigCheckAndSet(.existingTargetResource(existingTargetResource))
    }
    if let targetResourceCreationConfig = try container.decodeIfPresent(
      TargetResourceCreationConfig?.self, forKey: .targetResourceCreationConfig)
    {
      try resourceConfigCheckAndSet(.targetResourceCreationConfig(targetResourceCreationConfig))
    }
    self.resourceConfig = resourceConfig
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)

    if let choice = self.resourceConfig {
      switch choice {
      case .existingTargetResource(let value):
        try container.encode(value, forKey: .existingTargetResource)
      case .targetResourceCreationConfig(let value):
        try container.encode(value, forKey: .targetResourceCreationConfig)
      }
    }
  }

  /// The resource configuration for the target resource.
  public enum OneOf_ResourceConfig: Codable, Equatable, Sendable {
    /// Optional. The resource hierarchy node, in one of the following formats:
    ///
    /// - `organizations/{organizationID}`
    /// - `folders/{folderID}`
    /// - `projects/{projectID}`
    case existingTargetResource(Swift.String)
    /// Optional. The details that are required to create a resource and use
    /// that resource as the target resource for deployment.
    indirect case targetResourceCreationConfig(TargetResourceCreationConfig?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.cloudsecuritycompliance.v1.TargetResourceConfig"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
