// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// The details for a target resource.
public struct TargetResourceDetails: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// The framework deployment name for the target resource.
  ///
  /// For example,
  /// `organizations/{organization_id}/locations/{location}/frameworkDeployments/{framework_deployment_id}`
  public var frameworkDeployment: Swift.String = Swift.String()

  /// The display name of the target resource. For example, `google.com`,
  /// `staging-project`, or `development-folder`.
  public var targetResourceDisplayName: Swift.String = Swift.String()

  /// The target resource. For example, `organizations/1234567890`,
  /// `projects/1234567890`, or `folders/1234567890`.
  public var targetResource: Swift.String = Swift.String()

  /// The create time of the target resource.
  public var createTime: GoogleCloudWKT.Timestamp? = nil

  /// The update time of the target resource.
  public var updateTime: GoogleCloudWKT.Timestamp? = nil

  /// The major revision ID of the framework for the target resource.
  public var majorRevisionId: Swift.Int64 = Swift.Int64()

  /// The minor revision ID of the framework for the target resource.
  public var minorRevisionId: Swift.Int64 = Swift.Int64()

  /// Initialize a new instance of `TargetResourceDetails`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = TargetResourceDetails().with { $0.frameworkDeployment = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.cloudsecuritycompliance.v1.TargetResourceDetails"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
