// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// The configuration that's required to create a target resource.
public struct TargetResourceCreationConfig: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The configuration that's required to create the target resource.
  public var resourceCreationConfig: OneOf_ResourceCreationConfig? = nil

  /// Initialize a new instance of `TargetResourceCreationConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = TargetResourceCreationConfig().with { $0.folderCreationConfig = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case folderCreationConfig = "folderCreationConfig"
    case projectCreationConfig = "projectCreationConfig"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)

    var resourceCreationConfig: OneOf_ResourceCreationConfig? = nil
    let resourceCreationConfigCheckAndSet = {
      if resourceCreationConfig != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'resourceCreationConfig'"))
      }
      resourceCreationConfig = $0
    }
    if let folderCreationConfig = try container.decodeIfPresent(
      FolderCreationConfig?.self, forKey: .folderCreationConfig)
    {
      try resourceCreationConfigCheckAndSet(.folderCreationConfig(folderCreationConfig))
    }
    if let projectCreationConfig = try container.decodeIfPresent(
      ProjectCreationConfig?.self, forKey: .projectCreationConfig)
    {
      try resourceCreationConfigCheckAndSet(.projectCreationConfig(projectCreationConfig))
    }
    self.resourceCreationConfig = resourceCreationConfig
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)

    if let choice = self.resourceCreationConfig {
      switch choice {
      case .folderCreationConfig(let value):
        try container.encode(value, forKey: .folderCreationConfig)
      case .projectCreationConfig(let value):
        try container.encode(value, forKey: .projectCreationConfig)
      }
    }
  }

  /// The configuration that's required to create the target resource.
  public enum OneOf_ResourceCreationConfig: Codable, Equatable, Sendable {
    /// Optional. The configuration that's required to create a folder.
    indirect case folderCreationConfig(FolderCreationConfig?)
    /// Optional. The configuration that's required to create a project.
    indirect case projectCreationConfig(ProjectCreationConfig?)
  }

  public static var _anyTypeUrl: Swift.String {
    return
      "type.googleapis.com/google.cloud.cloudsecuritycompliance.v1.TargetResourceCreationConfig"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
