// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// The request message for [UpdateCloudControl][].
public struct UpdateCloudControlRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Optional. Use a field mask to specify the fields to be overwritten in the
  /// cloud control during the update.
  /// The fields that you specify in the `update_mask` are relative to the
  /// cloud control, not the full request. A field is overwritten if it is in
  /// the mask. If you don't provide a mask, all fields in the request
  /// are updated.
  ///
  /// You can update the following fields:
  ///
  /// - Display name
  /// - Description
  /// - Parameters
  /// - Rules
  /// - Parameter specification
  public var updateMask: GoogleCloudWkt.FieldMask? = nil

  /// Required. The cloud control that you're updating.
  public var cloudControl: CloudControl? = nil

  /// Initialize a new instance of `UpdateCloudControlRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = UpdateCloudControlRequest().with { $0.updateMask = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.cloudsecuritycompliance.v1.UpdateCloudControlRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
